const setOfWords =[
    "It’s a rainy day at my house. It’s rainy and windy. The pretty fall leaves are flying in my yard. They are beautiful. They are orange, red, brown, and gold. They are falling off the trees in my yard. I like to watch the leaves fly. The rain and wind make the leaves come off the trees. Soon the leaves will be all on the ground. I can help my mom and dad rake them up. I like this time of year.",
    "Dana loves the spring because she can go to the flower market to buy her annuals. The annuals only last one season, but they add a lot of colour to the garden. Dana got up Saturday morning very early. She wanted to get to the market early so she would have time to plant everything when she got home. Off she went to Barton’s Flower Market. She ran into some friends. Dana decided to buy red and yellow pansies, blue periwinkles, and purple petunias. That will add a lot of colour to my garden, thought Dana. She said goodbye to her friends and went home. ",
    "Once there lived a carpenter named Kasi. He had a five year old son. His name was Vasu. Kasi’s father Ramu was too old, and he also stayed with them. Kasi began to think that his father was of no use to him because he was too old to do any work. Kasi always spoke angrily to his father. One day, Kasi gave food in a mud plate to his father. Being too old, Ramu was not able to hold the mud plate. He dropped it down and broke it. Kasi became very angry and scolded his father. Vasu observed this. The next day, Kasi gave a new mud plate. He went out to work. ",
    "Plants need sunlight and water to make their own food. You can do an experiment to test if this is true. Place a bucket over a patch of green grass. After a few days, lift the bucket. You will see that the grass is not as green anymore. If you leave the bucket in place for a week, the grass will become very dull. This happens because the grass cannot make food in the dark. Remove the bucket. In a few days, the grass will start turning green again.",
    "I am thrilled that May is finally here! Now I can enjoy what I call “the sweet taste of summer”! Watermelons are in the stores, and I plan to eat one every day for the next three months. I think watermelons taste better than any other fruit. Peaches, plums, and strawberries are also great in the summer. I enjoy eating those, too. But they just don’t taste as good to me as a sweet, sweet watermelon. My whole family likes eating watermelons. We ate at least three watermelons a week last year. This year, I am going to eat watermelon every day, all summer long.",




];
export default setOfWords;
